---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12
  data_bags_path: data_bags
  encrypted_data_bag_secret_key_path: .chef/encrypted_data_bag_secret
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04
    driver:
      box: express42/ubuntu-14.04

suites:
  - name: tomcat-server
    run_list:
      - role[base]
      - role[java-sample]
